### PR TITLE
Support for net full + net core

### PR DESCRIPTION
**Pull request by rogalmic**
Some changes that I made today - sharing with community:
- update solution to VS2017 15.9.4
- make library to target common 'netstandard2.0'
- create .net Core sample
- update Clootils UI sample to .net framework 4.7.2 (from outdated 2.0)
- remove AMD hack from Clootils UI  (works on my AMD laptop)
- create VS Code configuration for .Net Core console app
- travis configuration for autobuilding (requires setting up token in github profile settings and set it to "GITHUB_TOKEN" variable in travis)
- newest C# language revision 7.3

Not sure if this is all needed, but at least could be some things to cherry-pick...

### CODE REVIEW

**Comment by TillAlex** [comment]
Thanks for sharing! Just one question: Is there any specific reason you are not using the develop branch? I already switched to netstandard 2.0 over there and also fixed some bugs.

**Comment by rogalmic** [comment]
No reason, I did not notice that...

**Comment by clSharp** [comment]
@rogalmic Just merged your changes into the master branch. 

I removed the .VS2017. parts from the project and solution files to make it consistent with my changes in the develop branch.

To be compatible with VS2017 I changed the frameworks used to .NET Core 2.0 and .NET 4.7.1

Hope this is ok for you...

**Comment by rogalmic** [comment]
No problem from my side, keep up the good work :)

**Pull request merged**
